name: Publish

on:
  push:
    branches:
    - main
jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - id: install-secret-key
      name: Install GPG secret key
      run: |
        cat <(echo -e "${{ secrets.GPG_SECRET_KEYS }}") | gpg --batch --import
